### ISSUE TITLE
Error save checkpoint

### ISSUE THREAD

**Issue by fbkarsdorp** [emanjavacas/seqmod#5]
Not sure where this is coming from:

```
[12-01 09:35:55] Epoch [9]; train loss: 2.96657; speed: 29108 tokens/sec
[12-01 09:38:38] Epoch [9]; valid loss: 3.07357
[12-01 09:38:38] Trained for [4963.611 sec]
[12-01 09:38:38] Testing...
[12-01 09:41:20] Test loss: 3.01202
Traceback (most recent call last):
  File "train_lm.py", line 202, in <module>
    u.save_checkpoint(args.save_path, best_model, d, args, ppl=test_loss)
  File "/home/folgert/venvs/anaconda/lib/python3.6/site-packages/seqmod-0.2-py3.6.egg/seqmod/utils.py", line 65, in save_checkpoint
TypeError: format() argument after ** must be a mapping, not Namespace
```

**Comment by emanjavacas** [comment]
This line https://github.com/emanjavacas/seqmod/blob/master/seqmod/utils.py#L60
`args` should be a dict, not a namespace. Probably something like `args = vars(args)` is missing.

**Comment by emanjavacas** [comment]
if you were using the built-in script, I've fixed it there with the last commit...

**Comment by fbkarsdorp** [comment]
Okay! Want me to make a PR?

**Comment by fbkarsdorp** [comment]
Ah, No. You closed it 👍
